# Configurações da aplicação
spring.application.name=srv-team

# Configurações do servidor
server.port=8082

# Configurações do MySQL Database (produção)
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configurações do JPA/Hibernate para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Configurações de logging
logging.level.com.example.srvteam=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO

# Configurações JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
