# Configurações da aplicação
spring.application.name=srv-team

# Configurações do servidor
server.port=8080

# Configurações do MySQL Database (produção)
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Console H2 desabilitado para MySQL
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# Configurações do JPA/Hibernate para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações de logging
logging.level.com.example.srvteam=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configurações JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
